Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-008e20914908f5345
      InstanceType: t2.micro
      KeyName: next-dev-key
      SecurityGroups:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: my-go-server