AWSTemplateFormatVersion: '2010-09-09'
Description: s3 + ec2 create

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  MyBucket:
    Type: AWS::S3::Bucket

  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-008e20914908f5345
      Tags:
        - Key: Name
          Value: my-go2

Outputs:
  InstanceId:
    Description: ec2 instance
    Value: !Ref MyInstance
